import Algorithms.SGD
import Lib.Glue.Algebra

open MeasureTheory ProbabilityTheory
open scoped InnerProductSpace

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
  [MeasurableSpace E] [BorelSpace E] [SecondCountableTopology E]
variable {S : Type*} [MeasurableSpace S]
variable {Ω : Type*} [MeasurableSpace Ω]

/-- The projected SGD process:
`w_{t+1} = proj (w_t - η_t • gradL(w_t, ξ_t))`. -/
noncomputable def pgdProcess (w₀ : E) (η : ℕ → ℝ) (gradL : E → S → E)
    (proj : E → E) (ξ : ℕ → Ω → S) : ℕ → Ω → E
  | 0 => fun _ => w₀
  | t + 1 => fun ω =>
      let w_t := pgdProcess w₀ η gradL proj ξ t ω
      proj (w_t - (η t) • gradL w_t (ξ t ω))

/-- Setup for projected GD: base SGD data + projection map with regularity assumptions. -/
structure ProjectedGDSetup
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]
      [MeasurableSpace E] [BorelSpace E]
    (S : Type*) [MeasurableSpace S]
    (Ω : Type*) [MeasurableSpace Ω] where
  toSGDSetup : SGDSetup E S Ω
  proj : E → E
  hproj_nonexp : ∀ x y, ‖proj x - proj y‖ ≤ ‖x - y‖
  hproj_meas : Measurable proj

namespace ProjectedGDSetup

variable (setup : ProjectedGDSetup E S Ω)

/-- Sample distribution inherited from the base setup. -/
noncomputable def sampleDist : Measure S :=
  setup.toSGDSetup.sampleDist

/-- The PGD random process derived from the setup. -/
noncomputable def process : ℕ → Ω → E :=
  pgdProcess setup.toSGDSetup.w₀ setup.toSGDSetup.η setup.toSGDSetup.gradL setup.proj setup.toSGDSetup.ξ

omit [SecondCountableTopology E] in
@[simp] theorem process_zero : setup.process 0 = fun _ => setup.toSGDSetup.w₀ := rfl

omit [SecondCountableTopology E] in
@[simp] theorem process_succ (t : ℕ) :
    setup.process (t + 1) = fun ω =>
      setup.proj (setup.process t ω -
        (setup.toSGDSetup.η t) •
          setup.toSGDSetup.gradL (setup.process t ω) (setup.toSGDSetup.ξ t ω)) := rfl

end ProjectedGDSetup

-- ============================================================================
-- Measurability and filtration for PGD
-- ============================================================================

omit [CompleteSpace E] in
/-- Each projected process iterate is measurable. -/
theorem pgdProcess_measurable {w₀ : E} {η : ℕ → ℝ}
    {gradL : E → S → E} {proj : E → E} {ξ : ℕ → Ω → S}
    (hξ : ∀ t, Measurable (ξ t))
    (hg : Measurable (Function.uncurry gradL))
    (hproj_meas : Measurable proj)
    (t : ℕ) : Measurable (pgdProcess w₀ η gradL proj ξ t) := by
  induction t with
  | zero =>
      exact measurable_const
  | succ t ih =>
      simp only [pgdProcess]
      exact hproj_meas.comp (ih.sub ((hg.comp (ih.prodMk (hξ t))).const_smul _))

omit [CompleteSpace E] in
/-- The projected process is adapted to the natural filtration generated by `ξ`. -/
theorem pgdProcess_adapted {w₀ : E} {η : ℕ → ℝ}
    {gradL : E → S → E} {proj : E → E} {ξ : ℕ → Ω → S}
    (hξ : ∀ t, Measurable (ξ t))
    (hg : Measurable (Function.uncurry gradL))
    (hproj_meas : Measurable proj) :
    Adapted (sgdFiltration ξ hξ) (fun t => pgdProcess w₀ η gradL proj ξ t) := by
  intro t
  induction t with
  | zero =>
      exact measurable_const
  | succ t ih =>
      simp only [pgdProcess]
      have h_wt : Measurable[sgdFiltration ξ hξ (t + 1)] (pgdProcess w₀ η gradL proj ξ t) :=
        ih.mono ((sgdFiltration ξ hξ).mono (Nat.le_succ t)) le_rfl
      have h_ξt : Measurable[sgdFiltration ξ hξ (t + 1)] (ξ t) := by
        rw [measurable_iff_comap_le]
        exact le_iSup₂_of_le t (Nat.lt_succ_self t) le_rfl
      exact hproj_meas.comp (h_wt.sub ((hg.comp (h_wt.prodMk h_ξt)).const_smul _))

omit [CompleteSpace E] in
/-- `pgdProcess t` is independent of the fresh sample `ξ t`.

Used in: Projected GD (Algorithms/ProjectedGD.lean, pgd_to_hyps — independence) -/
lemma pgdProcess_indepFun_xi
    {w₀ : E} {η : ℕ → ℝ} {gradL : E → S → E} {proj : E → E} {ξ : ℕ → Ω → S}
    {P : Measure Ω}
    (hξ_meas : ∀ t, Measurable (ξ t))
    (hξ_indep : iIndepFun (β := fun _ => S) ξ P)
    (hgL : Measurable (Function.uncurry gradL))
    (hproj_meas : Measurable proj)
    (t : ℕ) :
    IndepFun (pgdProcess w₀ η gradL proj ξ t) (ξ t) P := by
  set F := sgdFiltration ξ hξ_meas with hF_def
  have h_adapted : Measurable[F t] (pgdProcess w₀ η gradL proj ξ t) :=
    pgdProcess_adapted hξ_meas hgL hproj_meas t
  have h_comap_le :
      (inferInstance : MeasurableSpace E).comap (pgdProcess w₀ η gradL proj ξ t) ≤ F t :=
    measurable_iff_comap_le.mp h_adapted
  have h_iIndep : iIndep (fun i => (inferInstance : MeasurableSpace S).comap (ξ i)) P :=
    hξ_indep
  have h_filt_indep : Indep (F t) ((inferInstance : MeasurableSpace S).comap (ξ t)) P := by
    have h_le : ∀ i, (inferInstance : MeasurableSpace S).comap (ξ i) ≤ (inferInstance : MeasurableSpace Ω) :=
      fun i => (hξ_meas i).comap_le
    have h_disj : Disjoint ({j : ℕ | j < t}) ({t} : Set ℕ) :=
      Set.disjoint_left.mpr fun j hj ht => absurd (ht ▸ hj) (Nat.lt_irrefl t)
    have h_F_eq : F t = ⨆ j ∈ {j : ℕ | j < t},
        (inferInstance : MeasurableSpace S).comap (ξ j) := by
      simp [hF_def, sgdFiltration, Set.mem_setOf_eq]
    have h_sing : ⨆ i ∈ ({t} : Set ℕ),
        (inferInstance : MeasurableSpace S).comap (ξ i) =
        (inferInstance : MeasurableSpace S).comap (ξ t) := by
      simp
    rw [h_F_eq, ← h_sing]
    exact indep_iSup_of_disjoint h_le h_iIndep h_disj
  exact indep_of_indep_of_le_left h_filt_indep h_comap_le

-- ============================================================================
-- Bridge to Layer 1 meta-theorem hypotheses
-- ============================================================================

/-- Convert a projected setup at step `t` to `StochasticDescentHyps` for the virtual step.

Used in: Projected GD (Algorithms/ProjectedGD.lean, bridge) -/
noncomputable def pgd_to_hyps
    (setup : ProjectedGDSetup E S Ω) (t : ℕ)
    (hgL : Measurable (Function.uncurry setup.toSGDSetup.gradL))
    (hgF_meas : Measurable setup.toSGDSetup.gradF)
    (hunb : IsUnbiased setup.toSGDSetup.gradL setup.toSGDSetup.gradF setup.sampleDist) :
    StochasticDescentHyps E S Ω where
  P         := setup.toSGDSetup.P
  hP        := setup.toSGDSetup.hP
  ν         := setup.sampleDist
  wt        := setup.process t
  ξt        := setup.toSGDSetup.ξ t
  gradL     := setup.toSGDSetup.gradL
  gradF     := setup.toSGDSetup.gradF
  η         := setup.toSGDSetup.η t
  h_indep   := pgdProcess_indepFun_xi setup.toSGDSetup.hξ_meas setup.toSGDSetup.hξ_indep hgL
                 setup.hproj_meas t
  h_dist    := (setup.toSGDSetup.hξ_ident t).map_eq
  h_wt_meas := pgdProcess_measurable setup.toSGDSetup.hξ_meas hgL setup.hproj_meas t
  h_ξt_meas := setup.toSGDSetup.hξ_meas t
  hgL       := hgL
  hgF_meas  := hgF_meas
  hunb      := hunb

/-- Convex convergence for stochastic projected gradient descent.

The update is projected, so the proof combines:
1. non-expansiveness of projection (actual step ≤ virtual step),
2. `stochastic_descent_convex'` on the virtual step,
3. telescoping over `t < T`. -/
theorem pgd_convergence_convex_v2
    (setup : ProjectedGDSetup E S Ω) (f : E → ℝ) {L : NNReal} {σ η : ℝ} (wStar : E)
    (hgrad : IsGradientOf f setup.toSGDSetup.gradF)
    (hsmooth : IsLSmooth setup.toSGDSetup.gradF L)
    (hconvex : ConvexOn ℝ Set.univ f)
    (hvar : HasBoundedVariance setup.toSGDSetup.gradL setup.sampleDist σ)
    (hunb : IsUnbiased setup.toSGDSetup.gradL setup.toSGDSetup.gradF setup.sampleDist)
    (_hmin : IsMinimizer f wStar)
    (hproj_wStar : setup.proj wStar = wStar)
    (hη_pos : 0 < η) (hη : ∀ t, setup.toSGDSetup.η t = η)
    (T : ℕ) (hT : 0 < T)
    (hgL : Measurable (Function.uncurry setup.toSGDSetup.gradL))
    (h_intL : ∀ w, Integrable (setup.toSGDSetup.gradL w) setup.sampleDist)
    (h_int_f : ∀ t, Integrable (fun ω => f (setup.process t ω)) setup.toSGDSetup.P)
    (h_int_sq : ∀ t, Integrable (fun ω =>
        ‖setup.toSGDSetup.gradL (setup.process t ω) (setup.toSGDSetup.ξ t ω)‖ ^ 2)
      setup.toSGDSetup.P)
    (h_int_norm_sq : ∀ t, Integrable (fun ω =>
        ‖setup.process t ω - wStar‖ ^ 2) setup.toSGDSetup.P)
    (h_int_virtual : ∀ t, Integrable (fun ω =>
        ‖(setup.process t ω
          - setup.toSGDSetup.η t •
            setup.toSGDSetup.gradL (setup.process t ω) (setup.toSGDSetup.ξ t ω)) - wStar‖ ^ 2)
      setup.toSGDSetup.P)
    (h_int_inner : ∀ t, Integrable (fun ω =>
        ⟪setup.process t ω - wStar,
          setup.toSGDSetup.gradL (setup.process t ω) (setup.toSGDSetup.ξ t ω)⟫_ℝ)
      setup.toSGDSetup.P)
    (h_int_gF_inner : ∀ t, Integrable (fun ω =>
        ⟪setup.process t ω - wStar, setup.toSGDSetup.gradF (setup.process t ω)⟫_ℝ)
      setup.toSGDSetup.P) :
    (1 / (T : ℝ)) * ∑ t ∈ Finset.range T,
        (∫ ω, f (setup.process t ω) ∂setup.toSGDSetup.P - f wStar) ≤
      ‖setup.toSGDSetup.w₀ - wStar‖ ^ 2 / (2 * η * T) + η * σ ^ 2 / 2 := by
  haveI := setup.toSGDSetup.hP
  have hvar' : HasBoundedVariance' setup.toSGDSetup.gradL setup.sampleDist σ := by
    intro w
    exact hvar w
  have hstep : ∀ t < T,
      ∫ ω, ‖setup.process (t + 1) ω - wStar‖ ^ 2 ∂setup.toSGDSetup.P ≤
        ∫ ω, ‖setup.process t ω - wStar‖ ^ 2 ∂setup.toSGDSetup.P
        - 2 * η * (∫ ω, f (setup.process t ω) ∂setup.toSGDSetup.P - f wStar)
        + η ^ 2 * σ ^ 2 := fun t _ => by
    have h_proj_bound :
        ∫ ω, ‖setup.process (t + 1) ω - wStar‖ ^ 2 ∂setup.toSGDSetup.P ≤
          ∫ ω, ‖(setup.process t ω -
            setup.toSGDSetup.η t •
              setup.toSGDSetup.gradL (setup.process t ω) (setup.toSGDSetup.ξ t ω)) - wStar‖ ^ 2
            ∂setup.toSGDSetup.P := by
      apply integral_mono (h_int_norm_sq (t + 1)) (h_int_virtual t)
      intro ω
      simpa [ProjectedGDSetup.process_succ] using
        (proj_nonexp_sq setup.proj setup.hproj_nonexp
          (setup.process t ω - setup.toSGDSetup.η t •
            setup.toSGDSetup.gradL (setup.process t ω) (setup.toSGDSetup.ξ t ω))
          wStar hproj_wStar)
    have h_virtual :
        ∫ ω, ‖(setup.process t ω -
            setup.toSGDSetup.η t •
              setup.toSGDSetup.gradL (setup.process t ω) (setup.toSGDSetup.ξ t ω)) - wStar‖ ^ 2
            ∂setup.toSGDSetup.P ≤
          ∫ ω, ‖setup.process t ω - wStar‖ ^ 2 ∂setup.toSGDSetup.P
            - 2 * setup.toSGDSetup.η t *
                (∫ ω, f (setup.process t ω) ∂setup.toSGDSetup.P - f wStar)
            + (setup.toSGDSetup.η t) ^ 2 * σ ^ 2 :=
      stochastic_descent_convex'
        (pgd_to_hyps setup t hgL (hsmooth.continuous.measurable) hunb)
        f wStar hgrad hconvex hvar'
        (by show 0 < setup.toSGDSetup.η t; linarith [hη t])
        h_intL
        (h_int_inner t) (h_int_sq t) (h_int_norm_sq t) (h_int_f t) (h_int_gF_inner t)
    have h_comb := le_trans h_proj_bound h_virtual
    rwa [hη t] at h_comb
  have hsum : 2 * η * ∑ t ∈ Finset.range T,
        (∫ ω, f (setup.process t ω) ∂setup.toSGDSetup.P - f wStar) ≤
      ‖setup.toSGDSetup.w₀ - wStar‖ ^ 2 -
        ∫ ω, ‖setup.process T ω - wStar‖ ^ 2 ∂setup.toSGDSetup.P +
        (T : ℝ) * (η ^ 2 * σ ^ 2) := by
    set a := fun t => ∫ ω, ‖setup.process t ω - wStar‖ ^ 2 ∂setup.toSGDSetup.P
    set gap := fun t => ∫ ω, f (setup.process t ω) ∂setup.toSGDSetup.P - f wStar
    have h_rearr : ∀ t, t < T → 2 * η * gap t ≤ (a t - a (t + 1)) + η ^ 2 * σ ^ 2 :=
      fun t ht => by simp only [a, gap]; linarith [hstep t ht]
    have h_sum_le := Finset.sum_le_sum (fun t ht => h_rearr t (Finset.mem_range.mp ht))
    rw [← Finset.mul_sum] at h_sum_le
    simp only [Finset.sum_add_distrib, Finset.sum_const,
      Finset.card_range, nsmul_eq_mul] at h_sum_le
    have h_tele : ∑ t ∈ Finset.range T, (a t - a (t + 1)) = a 0 - a T := by
      simp_rw [show ∀ t, a t - a (t + 1) = -(a (t + 1) - a t) from fun t => by ring]
      rw [Finset.sum_neg_distrib, Finset.sum_range_sub]
      ring
    rw [h_tele] at h_sum_le
    have h_init : a 0 = ‖setup.toSGDSetup.w₀ - wStar‖ ^ 2 := by
      simp [a, ProjectedGDSetup.process, pgdProcess, integral_const, probReal_univ]
    rw [h_init] at h_sum_le
    linarith
  have h_norm_nonneg : 0 ≤ ∫ ω, ‖setup.process T ω - wStar‖ ^ 2 ∂setup.toSGDSetup.P :=
    integral_nonneg fun ω => sq_nonneg _
  have h_drop : 2 * η * ∑ t ∈ Finset.range T,
        (∫ ω, f (setup.process t ω) ∂setup.toSGDSetup.P - f wStar) ≤
      ‖setup.toSGDSetup.w₀ - wStar‖ ^ 2 + (T : ℝ) * (η ^ 2 * σ ^ 2) := by
    linarith
  have hT_pos : (0 : ℝ) < T := Nat.cast_pos.mpr hT
  have hη2_pos : (0 : ℝ) < 2 * η := by linarith
  rw [one_div, inv_mul_le_iff₀ hT_pos]
  have h_rhs : ↑T * (‖setup.toSGDSetup.w₀ - wStar‖ ^ 2 / (2 * η * ↑T) + η * σ ^ 2 / 2) =
      (‖setup.toSGDSetup.w₀ - wStar‖ ^ 2 + ↑T * (η ^ 2 * σ ^ 2)) / (2 * η) := by
    field_simp
  rw [h_rhs, le_div_iff₀ hη2_pos]
  linarith

